### ISSUE TITLE
Issue with deserializing on PUT

### ISSUE THREAD

**Issue by Mivaweb** [Mexia/PowerShell#2]
Hi,

I am having problems with this script, any idea?

```
# This script is intended to be used for PowerShell script tasks in VSTS in "inline mode" 

$valueName = 'ProjectBuildVersion'
$token = 'MYCODE'

$uriRoot = $env:SYSTEM_TEAMFOUNDATIONSERVERURI
$ProjectName = $env:SYSTEM_TEAMPROJECT
$ProjectId = $env:SYSTEM_TEAMPROJECTID 
$uri = "$uriRoot$ProjectName/_apis/build/definitions?api-version=2.0"

# Base64-encodes the Personal Access Token (PAT) appropriately
$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "", $token)))
$header = @{Authorization = ("Basic {0}" -f $base64AuthInfo)}

# Get the list of Build Definitions
$buildDefs = Invoke-RestMethod -Uri $uri -Method Get -ContentType "application/json" -Headers $header
 
# Find the build definition for this project
$buildDef = $buildDefs.value | Where-Object { $_.Project.id -eq $ProjectId }

if ($buildDef -eq $null)
{
    Write-Error "Unable to find a build definition for Project '$ProjectName'. Check the config values and try again." -ErrorAction Stop
}
# NOTE: ensure we call the v 2.0 api! (both get and put calls NEED the same api versions!)
# get its details
$projectDef = Invoke-RestMethod -Uri "$($buildDef.Url)?api-version=2.0" -Method Get -ContentType "application/json" -Headers $header

if ($projectDef.variables.$valueName -eq $null)
{
    Write-Error "Unable to find a variable called '$valueName' in Project $ProjectName. Please check the config and try again." -ErrorAction Stop
}
# get and increment the variable in $valueName
[int]$counter = [convert]::ToInt32($projectDef.variables.$valueName.Value, 10)
$updatedCounter = $counter + 1
Write-Host "Project Build Number for '$ProjectName' is $counter. Will be updating to $updatedCounter"

# Update the value and update VSTS
$projectDef.variables.ProjectBuildVersion.Value = $updatedCounter.ToString()
$projectDefJson = $projectDef | ConvertTo-Json -Depth 50 -Compress
Invoke-RestMethod -Method Put -Uri "$($projectDef.Url)&api-version=2.0" -Headers $header -ContentType "application/json" -Body $projectDefJson | Out-Null
```

```
Invoke-RestMethod : {"$id":"1","innerException":null,"message":"This request expects an object in the request body, 
but the supplied data could not be 
deserialized.","typeName":"Microsoft.TeamFoundation.Build.WebApi.RequestContentException, 
Microsoft.TeamFoundation.Build2.WebApi, Version=14.0.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a","typeKey":"RequestContentException","errorCode":0,"eventId":3000}
At D:\a\_temp\231f1be5-edc0-4bd9-a2e4-efd23a8308d1.ps1:42 char:1
+ Invoke-RestMethod -Method Put -Uri "$($projectDef.Url)&api-version=2. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

Thanks!

/Michaël

**Comment by Mivaweb** [comment]
The only difference is the variable name which is in my case `ProjectBuildVersion`

Thx!

**Comment by mattcorr** [comment]
Hello @Mivaweb , I have updated the script. Issue #1 also addresses this same issue.

It should work for you, after you update your variable name to `ProjectBuildVersion`. 

Thanks for bringing this to my attention!

**Comment by Mivaweb** [comment]
Hi mattcorr,

tried it but still the same issue:

Invoke-RestMethod : {"$id":"1","innerException":null,"message":"This request expects an object in the request body, 
but the supplied data could not be 
deserialized.","typeName":"Microsoft.TeamFoundation.Build.WebApi.RequestContentException, 
Microsoft.TeamFoundation.Build2.WebApi, Version=14.0.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a","typeKey":"RequestContentException","errorCode":0,"eventId":3000}
At D:\a\_temp\9f085422-ab7a-4154-8420-7cc1642644f8.ps1:51 char:1
+ Invoke-RestMethod -Method Put -Uri $putUrl -Headers $header -ContentT ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Using VSTS online

/Michaël

**Comment by Mivaweb** [comment]
Even when I update the variable name to the one you use, I got the same exception.
Something wrong with the json body but won't know whats causing this problem because we just edit a property in it.

/Michaël

**Comment by Mivaweb** [comment]
Ok solved it. Problem was the convertto-json replaces some characters like & to \u0026. With the following it get solved:

`Invoke-RestMethod -Method Put -Uri $putUrl -Headers $header -ContentType "application/json" -Body ([System.Text.Encoding]::UTF8.GetBytes($projectDefJson)) | Out-Null`

**Comment by mattcorr** [comment]
Thats an odd one. Are you able to provide a view of what the json body looks like? I want to test something from my end

**Comment by Mivaweb** [comment]
Also I had to use api-version 4.1 because using 2.0 it removed all tasks and params from my build definition. I think it all depends on which version you are running VSTS?

They should documents this better.

/Michaël

**Comment by mattcorr** [comment]
I found out during development, if you used the same version of the API for when you `get` and `put` the variables, then it was fine. But if you used different API versions, you are in a world of hurt. 

I tested the above with version 2.0 last night and it worked. 

I was not aware API 4.1 was out. Will have to look at that as well.

**Comment by Mivaweb** [comment]
Yes correct but I was using the same version for GET and PUT. Now with the latest VSTS it only works completely using version 4.1.

/Michaël

**Comment by mattcorr** [comment]
yes, you are right. I'll look into it later tonight. Thanks!

**Comment by mattcorr** [comment]
Have updated the code. Feel free to try that. I have tested in my VSTS and it updates the variable and does not blow away the Build's process steps!
